### PR TITLE
[KAT-6321] Add dataset for label propagation

### PR DESCRIPTION
**Pull request by srogatch**
These are the datasets for https://github.com/KatanaGraph/katana-enterprise/pull/3886

### CODE REVIEW

**Comment by chakpongchung** [comment]
There is an infinity symbol in "Files changed". What have you done? :)

**Comment by srogatch** [comment]
> There is an infinity symbol in "Files changed". What have you done? :)

I added some binary files, because that's what this repo contains. These files are the input graphs for label propagation.

**Comment by chakpongchung** [comment]
> > There is an infinity symbol in "Files changed". What have you done? :)
> 
> I added some binary files, because that's what this repo contains. These files are the input graphs for label propagation.

My experience shows storing large binary files in a git repo is a bad idea. If you can it many times enough, the size of the git repo can explode due to the large git change history. 

The approval is mainly for your convenience. By the time the git history is too large, we will need to fix it.

**Review by chakpongchung — APPROVED** [review]

**Comment by srogatch** [comment]
@chakpongchung I agree, we need at least `git-lfs` for such data. It's however our process to store the input graphs for the automatic tests and the goal outputs in this git repo.

**Comment by yshalabi** [comment]
Merging this was not a good idea. And I hope in the future @chakpongchung you would block a PR like this from merging and that @srogatch you would recognize the need for another solution to begin with.

For your information, this one PR added 3.6 GB out of the total 4GB of this repo.

It also created systemic problems for us to solve because the number of files is unreasonably large for minikube mounts https://minikube.sigs.k8s.io/docs/handbook/mount/#9p-mounts 

cc @ddn0 @bowu @patrickkenney9801

**Comment by srogatch** [comment]
@yshalabi after that, I started a task to reduce the dataset size; however, it is blocked by missing features in API1 and API2, C++ and Python: https://katanagraph.atlassian.net/browse/KAT-9063 . Basically, we need a way to compact the graph after the nodes are removed, otherwise, the properties retain the original number of rows. I didn't know that there is no way to create a subgraph in Katana.

**Comment by bowu** [comment]
@srogatch Can you use a smaller dataset? We have multiple small graphs with vector data available.

**Comment by srogatch** [comment]
@bowu sure, if someone tells me which not-too-small graphs have vector properties of type `float` (if there are `float`s as fixed-size binary, that's also fine), I can change the input graph. However, this is not a completely trivial task because it requires the generation of the `verify` outputs too. So it requires a focus switch for some time, thus for productivity, I would suggest I start with this task on Monday because tomorrow I need to finish in-edges distribution to the other hosts.

**Pull request merged**
