### PR TITLE
rmat10, DLSPG, partitioned for 6 hosts

### PR DESCRIPTION
**Pull request by witchel**
### PR Checklist

* [ ] test-datasets is a publicly accessible github repo. The contents of this PR can be made public.
* [ ] The naming and organization of the dataset I am adding follows https://github.com/KatanaGraph/test-datasets#organization
* [ ] If I am adding an RDG, its directory contains a (import/migrate/generate) script, and a README describing the RDGs usage. https://github.com/KatanaGraph/test-datasets#the-following-scripts-are-conditionally-present-for-each-rdg-one-of-the-following-options-must-be-present
* [ ] If I am uprevving the storage_format_version of the rdgs in this repo, I have followed https://github.com/KatanaGraph/test-datasets#how-to-uprev-the-rdgs-in-this-repo

### List of folks that should be notified of this PR. Please don't remove these. 
@scober
@aneeshdurg

Useful LSPG partitioned graph for testing.

### CODE REVIEW

**Review by BartoKatana — APPROVED** [review]
A very large collection of binary files with a new manifest indicating 6 hosts. What's not to like?

**Comment by witchel** [comment]
> A very large collection of binary files with a new manifest indicating 6 hosts. What's not to like?

It is ~2MB, which is kind of large.  About 4x larger than the unpartitioned graph.

**Comment by witchel** [comment]
> Please add scripts for generating this dataset and a README describing it
> 
> https://github.com/KatanaGraph/test-datasets#the-following-scripts-are-conditionally-present-for-each-rdg-one-of-the-following-options-must-be-present

Well, I wonder about this.  I think our current process is overdesigned and broken.

I could add a README.  It would say rmat10 DLSPG, partitioned for 6 hosts.  But all of that information is already available via file names.

As it is, I did not include the partitioning policy in the file name as other data sets do.  We now have different node and edge policies, which is not reflected in these file names.  This experience convinces me that it is best to avoid reencoding this metadata into file names.

All of the current uprev tooling is broken.  For example, it assumes version numbers are integers, but it is a string for LSPG.

Finally, I couldn't even generate this dataset myself using current APIs (see [KAT-11702]).  I had Milos generate it for me.  I could document that, but would it be valuable?

**Comment by scober** [comment]
Those are all fair points, but I think overdesigned, broken and consistent is still better than overdesigned, broken, and inconsistent. Could you try to get scripts from @gliga that capture generating this dataset? I know it won't be useful because `uprev` is broken but I think it will be easier to do now than in the future when `uprev` is fixed or there is some other updating procedure in place.

As for the README, it should include information like why no other dataset in the repo was usable as a replacement for this one or why a dataset could not be generated in memory for the tests that use it.

**Comment by witchel** [comment]
> Those are all fair points, but I think overdesigned, broken and consistent is still better than overdesigned, broken, and inconsistent. Could you try to get scripts from @gliga that capture generating this dataset? I know it won't be useful because `uprev` is broken but I think it will be easier to do now than in the future when `uprev` is fixed or there is some other updating procedure in place.
> 
> As for the README, it should include information like why no other dataset in the repo was usable as a replacement for this one or why a dataset could not be generated in memory for the tests that use it.

My great aunt Wilma used to say, "nerds argue to the death over trivialities."  I always thought old Wilma was a sage, but I am convinced by your argument and will provide additional background.

**Comment by gliga** [comment]
When I was importing the graph I was not aware things will evolve into this story :).

First, I suggest we pick a much smaller graph if we are to use it in our CI tests.  Happy to generate and import a small graph.  Actually, you can do it on your own with our new graphgen tool.  It is wonderful.  You can ask @farahhariri how to use the tool or you can read documentation (on the docs page) or we can do it for you :).  
You can pick min number of nodes, edges, properties, types and we get csv files (or parquet or whatever needed) and then we can use regular import to get rdg as desired.

I will not argue over other things in light of recent comments :).

**Comment by witchel** [comment]
> When I was importing the graph I was not aware things will evolve into this story :).
> 
> First, I suggest we pick a much smaller graph if we are to use it in our CI tests. Happy to generate and import a small graph. Actually, you can do it on your own with our new graphgen tool. It is wonderful. You can ask @farahhariri how to use the tool or you can read documentation (on the docs page) or we can do it for you :). You can pick min number of nodes, edges, properties, types and we get csv files (or parquet or whatever needed) and then we can use regular import to get rdg as desired.
> 
> I will not argue over other things in light of recent comments :).

Ok, I'll look at graphgen.

I'll just note that I have spent about as much time trying to generate a valid test as I did writing the flatbuffer code to begin with.

**Comment by scober** [comment]
> I'll just note that I have spent about as much time trying to generate a valid test as I did writing the flatbuffer code to begin with.

That sucks and I think we should put some test datasets redesigning in the planning pipeline if we can.

**Pull request closed without merging**
