### PR TITLE
Add 2 node graph with two self loops and AI properties

### PR DESCRIPTION
**Pull request by l-hoang**
This commit contains a two node graph each with a self loop. The graph
has AI properties, specifically a label, a split, and a 2 length feature
vector.

A README containing generation instructions is included as well; because
csv-import doesn't support feature vectors, there is a manual component
to generation. A migrate script exists as well to move from storage
version to storage version as necessary.

### CODE REVIEW

**Comment by e-mcginnis** [comment]
Overall, looks great Loc. Could we put the csv data that is currently in `generation`  in `csv_datasets/two_self_loops_ai` instead and update the README accordingly?

**Comment by l-hoang** [comment]
Moved the csvs to `csv_datasets`

**Comment by e-mcginnis** [comment]
> > Overall, looks great Loc. Could we put the csv data that is currently in `generation` in `csv_datasets/two_self_loops_ai` instead and update the README accordingly?
> 
> Sure; that's the only change you want, correct?
> 

yep! 

> By the way, slightly orthogonal question, but it seems that the `get_rdg_dataset` call thinks storage format 6 is the latest version even though my creation of this RDG put me at format 7; do you have any insight on that?

Hm, that is weird. Could your build or sha be stale? I'm seeing the latest version reported as `7` on my machine.

**Review by e-mcginnis — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
