### PR TITLE
Add LSPG RDG version for LDBC_003

### PR DESCRIPTION
**Pull request by bhargavivadali**
### PR Checklist

* [ ] test-datasets is a publicly accessible github repo. The contents of this PR can be made public.
* [ ] The naming and organization of the dataset I am adding follows https://github.com/KatanaGraph/test-datasets#organization
* [ ] If I am adding an RDG, its directory contains a (import/migrate/generate) script, and a README describing the RDGs usage. https://github.com/KatanaGraph/test-datasets#the-following-scripts-are-conditionally-present-for-each-rdg-one-of-the-following-options-must-be-present
* [ ] If I am uprevving the storage_format_version of the rdgs in this repo, I have followed https://github.com/KatanaGraph/test-datasets#how-to-uprev-the-rdgs-in-this-repo

### List of folks that should be notified of this PR. Please don't remove these. 
@scober
@aneeshdurg

Adding  LSPG RDG version for LDBC_003. The files are from `gs://katana-demo-datasets/rdg-datasets/dslg1.stpg0/ldbc_003_`  [KAT-9410]

[KAT-9410]: https://katanagraph.atlassian.net/browse/KAT-9410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by gliga** [comment]
Is it necessary to add extra characters in the name and make it diff from the online name? @scober

**Comment by aneeshdurg** [comment]
@gliga what do you mean online name?

**Comment by aneeshdurg** [comment]
@bhargavivadali thanks for doing this for ldbc003, but can we just uprev everything via the uprev scripts here?

**Comment by gliga** [comment]
@aneeshdurg we are simply using gs://katana-demo-datasets/rdg-datasets/dslg1.stpg0/ldbc_003_ in buckets.  My question why do we need all those extra chars in the name "version" etc.

**Comment by gliga** [comment]
@aneeshdurg I believe that we cannot use uprev here.  Old RDGs are not correct, so we are moving the one imported on a deployed system.  Old RDGs should go away if you ask me.

**Comment by aneeshdurg** [comment]
hmm, I see. In that case I might advocate for deleting all old version of ldbc003 in this PR or a followup to avoid confusion. @scober thoughts?

The goal for this repo is that uprev should always work for upgrading to the next version, but this isn't just an upgrade - it's changing the graph itself.

**Comment by gliga** [comment]
That is correct.

Regarding old versions.  @bhargavivadali and I discussed and it seems the best to do it in a separate PR.  The reason is that some tests still depend on old RDGs and that is delicate update that will require a separate change.  I will send you our Jira ticket planned for this upgrade.

**Comment by bhargavivadali** [comment]
> hmm, I see. In that case I might advocate for deleting all old version of ldbc003 in this PR or a followup to avoid confusion. @scober thoughts?
> 
> The goal for this repo is that uprev should always work for upgrading to the next version, but this isn't just an upgrade - it's changing the graph itself.

We cannot currently delete older versions as some ctests are still using them.

**Review by aneeshdurg — APPROVED** [review]
Since the future work is tracked, I see no reason to block this from merging. Once the old ldbc003 is deleted we should still uprev all the other rdgs soon.

**Review by gliga — APPROVED** [review]
LG

Thanks!

**Comment by scober** [comment]
I am about a day late but I want to add one comment about old datasets for posterity. I would like to preserve at least one dataset (and preferably more than one (and ldbc would be a good one to keep)) in every supported version. As long as we are supporting a given RDG version we should be testing that we can load RDGs of that version.

**Comment by gliga** [comment]
@scober that is fine.  We can keep those RDGs and I agree with you that testing on old RDG formats is important. However, my understanding is that we are still not in the mode of supporting old/legacy storage formats.  Also, some of those versions had known bugs.

At this point we officially support only dslg1.stpg0 format (and no prior format although things can work).
@tylershunt should probably provide input here.

**Comment by scober** [comment]
If we don't plan on supporting old storage format versions then I think we should be explicit about that: we should not keep old storage format versions in this repository, we should not attempt to load and upgrade RDGs that are in old versions, etc. I don't love the idea of supporting old versions halfway.

**Comment by gliga** [comment]
Maybe we started mixing several things here.  Here are the key points:

* We do plan to support old formats and to be backward compatible
* We do NOT plan to support RDG formats prior to the lspg
* Having v9 around and lspg should be sufficient at this point for testing.

**Comment by scober** [comment]
Points 2 and 3 seem conflicting to me

**Comment by gliga** [comment]
Let me supplement that with the following view:
* We need v9 at this point because some applications do not work with the lspg format (so hard to beat this one)
* We should not be biased by the versions that will eventually be used by users and we should use any opportunity to set up the update tests in place with what we have available (so thus having v9 in addition to lspg is good). The same set of tests should be able to be used once we have officially supported versions.

**Pull request merged**
