### PR TITLE
LSPG7 RDGs for gnn, rgcn, financial_300 datasets

### PR DESCRIPTION
**Pull request by bhargavivadali**
### PR Checklist

* [ ] test-datasets is a publicly accessible github repo. The contents of this PR can be made public.
* [ ] The naming and organization of the dataset I am adding follows https://github.com/KatanaGraph/test-datasets#organization
* [ ] If I am adding an RDG, its directory contains a (import/migrate/generate) script, and a README describing the RDGs usage. https://github.com/KatanaGraph/test-datasets#the-following-scripts-are-conditionally-present-for-each-rdg-one-of-the-following-options-must-be-present
* [ ] If I am uprevving the storage_format_version of the rdgs in this repo, I have followed https://github.com/KatanaGraph/test-datasets#how-to-uprev-the-rdgs-in-this-repo

### List of folks that should be notified of this PR. Please don't remove these. 
@scober
@aneeshdurg

LSPG7 RDGs for gnn, rgcn, financial_300 datasets [KAT-16415] [KAT-16402] [KAT-16406] [KAT-16407] [KAT-16408]

[KAT-16415]: https://katanagraph.atlassian.net/browse/KAT-16415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KAT-16402]: https://katanagraph.atlassian.net/browse/KAT-16402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KAT-16406]: https://katanagraph.atlassian.net/browse/KAT-16406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by gliga** [comment]
Are we using these datasets in tests?  If not, we should not be including them.

**Comment by bhargavivadali** [comment]
> Are we using these datasets in tests? If not, we should not be including them.

Yes most of these are used in tests except financial_300. It was added couple of weeks ago but didn't find any tests in enterprise repo.

**Comment by gliga** [comment]
Let's remove those that are not used (e.g., financial_300).

**Review by gliga — APPROVED** [review]
LG but please do not include data we do not use in any test (and remove any data from the repo that is not used).

**Comment by bhargavivadali** [comment]
> Let's remove those that are not used (e.g., financial_300).

@johnbowen42 Is it ok to remove financial_300 CSV and RDG files? I couldn't find any tests using them.

**Pull request merged**
