### PR TITLE
Add rmat10 and rmat15 lspg datasets

### PR DESCRIPTION
**Pull request by bhargavivadali**
### PR Checklist

* [ ] test-datasets is a publicly accessible github repo. The contents of this PR can be made public.
* [ ] The naming and organization of the dataset I am adding follows https://github.com/KatanaGraph/test-datasets#organization
* [ ] If I am adding an RDG, its directory contains a (import/migrate/generate) script, and a README describing the RDGs usage. https://github.com/KatanaGraph/test-datasets#the-following-scripts-are-conditionally-present-for-each-rdg-one-of-the-following-options-must-be-present
* [ ] If I am uprevving the storage_format_version of the rdgs in this repo, I have followed https://github.com/KatanaGraph/test-datasets#how-to-uprev-the-rdgs-in-this-repo

### List of folks that should be notified of this PR. Please don't remove these. 
@scober
@aneeshdurg

Adding rmat10 and rmat15 lspg datasets. These datasets are from `gs://katana-demo-datasets/rdg-datasets/dslg1.stpg0/`.
Removing old ldbc 003 dir.

### CODE REVIEW

**Comment by scober** [comment]
I'm not convinced that we should be removing the old LDBCs yet. It is a graph with a lot of properties and tags which makes it ideal for testing loading old storage format versions.

**Comment by bhargavivadali** [comment]
> I'm not convinced that we should be removing the old LDBCs yet. It is a graph with a lot of properties and tags which makes it ideal for testing loading old storage format versions.

We still have all the old ldbc versions in ldbc_003 directory. When updating ldbc csv dataset, I made a copy of the previous dir and saved it as ldbc_old. Im only removing the redundant dir.

**Comment by scober** [comment]
@bhargavivadali does the data in the newest version of ldbc match the data in the older versions of ldbc?

**Comment by bhargavivadali** [comment]
> @bhargavivadali does the data in the newest version of ldbc match the data in the older versions of ldbc?



> @bhargavivadali does the data in the newest version of ldbc match the data in the older versions of ldbc?

The number of nodes and edges don't match.

> > I'm not convinced that we should be removing the old LDBCs yet. It is a graph with a lot of properties and tags which makes it ideal for testing loading old storage format versions.
> 
> We still have all the old ldbc versions in ldbc directory. When updating ldbc csv dataset, I made a copy of the previous dir and saved it as ldbc_old. Im only removing the redundant dir.



> @bhargavivadali does the data in the newest version of ldbc match the data in the older versions of ldbc?

The new version has more nodes and edges than older version.

**Comment by scober** [comment]
But the directory we are removing contains exact duplicates of what is already in the current ldbc directory?

**Comment by bhargavivadali** [comment]
Closing this PR. I will open a new PR for updating mat datasets. Will confirm if the new ldbc dataset has same data as older rev with additional nodes/edges and create a separate PR for it.

**Pull request closed without merging**
