### PR TITLE
Remove unused datasets- Epinions, Arxiv, ldbc_003_split_prop, and partitioned_smiles_small

### PR DESCRIPTION
**Pull request by bhargavivadali**
### PR Checklist

* [ ] test-datasets is a publicly accessible github repo. The contents of this PR can be made public.
* [ ] The naming and organization of the dataset I am adding follows https://github.com/KatanaGraph/test-datasets#organization
* [ ] If I am adding an RDG, its directory contains a (import/migrate/generate) script, and a README describing the RDGs usage. https://github.com/KatanaGraph/test-datasets#the-following-scripts-are-conditionally-present-for-each-rdg-one-of-the-following-options-must-be-present
* [ ] If I am uprevving the storage_format_version of the rdgs in this repo, I have followed https://github.com/KatanaGraph/test-datasets#how-to-uprev-the-rdgs-in-this-repo

### List of folks that should be notified of this PR. Please don't remove these. 
@scober
@aneeshdurg

Remove unused datasets- Epinions [KAT-16397], Arxiv [KAT-16398], ldbc_003_split_prop [KAT-16411], and partitioned_smiles_small [KAT-16413] 

[KAT-16397]: https://katanagraph.atlassian.net/browse/KAT-16397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KAT-16398]: https://katanagraph.atlassian.net/browse/KAT-16398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KAT-16413]: https://katanagraph.atlassian.net/browse/KAT-16413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[KAT-16411]: https://katanagraph.atlassian.net/browse/KAT-16411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by gliga — APPROVED** [review]
LG

**Comment by astolman** [comment]
@l-hoang are we good to get rid of the arxiv rdg?

**Comment by gliga** [comment]
Note that this is for CI only (test-datasets)

**Review by l-hoang — APPROVED** [review]
just grep'd to see if any test was using it and it looks like it's fine to remove

there's an old unused fixture that refers to it that we can get rid of later

**Review by scober — APPROVED** [review]

**Pull request merged**
