### PR TITLE
Add 3 node graph with many self loops and a sink node

### PR DESCRIPTION
**Pull request by l-hoang**
### PR Checklist

* [x] test-datasets is a publicly accessible github repo. The contents of this PR can be made public.
* [x] The naming and organization of the dataset I am adding follows https://github.com/KatanaGraph/test-datasets#organization
* [x] If I am adding an RDG, its directory contains a (import/migrate/generate) script, and a README describing the RDGs usage. https://github.com/KatanaGraph/test-datasets#the-following-scripts-are-conditionally-present-for-each-rdg-one-of-the-following-options-must-be-present
* [x] If I am uprevving the storage_format_version of the rdgs in this repo, I have followed https://github.com/KatanaGraph/test-datasets#how-to-uprev-the-rdgs-in-this-repo

### List of folks that should be notified of this PR. Please don't remove these. 
@e-mcginnis
@aneeshdurg

-----

This commit adds a 3 node graph where 2 nodes have many self loops (one
has 3, the other has 9), and both of these self loop nodes connect to a
sink node via an outgoing edge. The graph has dummy AI features and
actual feature vectors for use with AI tests.

This graph is for me to test arbitrary degree support
(the other self loop graph only has a single loop for the two
nodes so it can't be used to test arbitrary degrees) and to test
outgoing vs incoming sampling via the sink node.

### CODE REVIEW

**Comment by l-hoang** [comment]
> Since the steps to generate the rdg are well known, can we have a generate.py script that follows the conventions set out in the root Readme?

No, because the feature import requires katana_enterprise code (not public) to work, so the uprev would still need to use the already generated RDG.

**Comment by e-mcginnis** [comment]
> No, because the feature import requires katana_enterprise code (not public) to work, so the uprev would still need to use the already generated RDG.

The uprev import/generate/migrate scripts already rely on a build katana-enterprise codebase to preform the uprev process, so this is not true.

**Comment by l-hoang** [comment]
> > No, because the feature import requires katana_enterprise code (not public) to work, so the uprev would still need to use the already generated RDG.
> 
> The uprev import/generate/migrate scripts already rely on a build katana-enterprise codebase to preform the uprev process, so this is not true.

In that case I can import katana_enterprise in uprev scripts?

**Comment by e-mcginnis** [comment]
> > > No, because the feature import requires katana_enterprise code (not public) to work, so the uprev would still need to use the already generated RDG.
> > 
> > 
> > The uprev import/generate/migrate scripts already rely on a build katana-enterprise codebase to preform the uprev process, so this is not true.
> 
> In that case I can import katana_enterprise in uprev scripts?

that is not straightforward, but you can shell out (gross, I know) to call your script

**Comment by l-hoang** [comment]
would something like this not work?
```
 24 def uprev(config: Config, new_storage_format_version: int) -> pathlib.Path:                                                                                                                            [0/1927] 25     available_csv = csv_datasets.available_csv()
 26     if csv_dataset not in available_csv:
 27         raise RuntimeError("csv dataset {} not in available csv_datasets: {}".format(csv_dataset, available_csv))
 28
 29     return_path = rdg_import.import_(
 30         config=config,
 31         rdg_path=local_path,
 32         out_ver=new_storage_format_version,
 33         csv_path=csv_path,
 34         node_file=node_file,
 35         edge_file=edge_file,
 36         import_args=import_args,
 37     )
 38
 39     # add features
 40     print(return_path)
 41
 42     distributed.initialize()
 43
 44     # IMPORTANT:
 45     # assumes GIDs are maintained on load for a single node; i.e., the node with
 46     # GID 2 should get 5,5 because it's the sink node
 47     features_numpy = np.array([[1, 1], [1, 1], [5, 5]], np.float32)
 48     features_numpy = np.ascontiguousarray(features_numpy)
 49
 50     # dist prop graph
 51     print("Loading RDG", flush=True)
 52     original_graph = Graph(local_path)
 53
 54     print("rdg loaded",flush=True)
 55
 56     number_of_nodes = original_graph.num_nodes()
 57     assert number_of_nodes == features_numpy.shape[0]
 58
 59     # the total number of bytes in a feature vector of a node
 60     pa_type = pyarrow.binary(features_numpy.dtype.itemsize * features_numpy.shape[1])
 61     arrow_buffer = pyarrow.py_buffer(features_numpy.data)
 62     buffers = [None, arrow_buffer]
 63     # creates pyarrow wrapper over the numpy array
 64     pyarrow_array = pyarrow.Array.from_buffers(pa_type, number_of_nodes, buffers=buffers)
 65
 66     print("craeted pyarrow array",flush=True)
 67
 68     # to table
 69     table = pyarrow.Table.from_arrays([pyarrow_array], ["feature"])
 70     # save to in-memory graph
 71     original_graph.upsert_node_property(table)
```

**Comment by e-mcginnis** [comment]
> would something like this not work?
> 
> ```
>  24 def uprev(config: Config, new_storage_format_version: int) -> pathlib.Path:                                                                                                                            [0/1927] 25     available_csv = csv_datasets.available_csv()
>  26     if csv_dataset not in available_csv:
>  27         raise RuntimeError("csv dataset {} not in available csv_datasets: {}".format(csv_dataset, available_csv))
>  28
>  29     return_path = rdg_import.import_(
>  30         config=config,
>  31         rdg_path=local_path,
>  32         out_ver=new_storage_format_version,
>  33         csv_path=csv_path,
>  34         node_file=node_file,
>  35         edge_file=edge_file,
>  36         import_args=import_args,
>  37     )
>  38
>  39     # add features
>  40     print(return_path)
>  41
>  42     distributed.initialize()
>  43
>  44     # IMPORTANT:
>  45     # assumes GIDs are maintained on load for a single node; i.e., the node with
>  46     # GID 2 should get 5,5 because it's the sink node
>  47     features_numpy = np.array([[1, 1], [1, 1], [5, 5]], np.float32)
>  48     features_numpy = np.ascontiguousarray(features_numpy)
>  49
>  50     # dist prop graph
>  51     print("Loading RDG", flush=True)
>  52     original_graph = Graph(local_path)
>  53
>  54     print("rdg loaded",flush=True)
>  55
>  56     number_of_nodes = original_graph.num_nodes()
>  57     assert number_of_nodes == features_numpy.shape[0]
>  58
>  59     # the total number of bytes in a feature vector of a node
>  60     pa_type = pyarrow.binary(features_numpy.dtype.itemsize * features_numpy.shape[1])
>  61     arrow_buffer = pyarrow.py_buffer(features_numpy.data)
>  62     buffers = [None, arrow_buffer]
>  63     # creates pyarrow wrapper over the numpy array
>  64     pyarrow_array = pyarrow.Array.from_buffers(pa_type, number_of_nodes, buffers=buffers)
>  65
>  66     print("craeted pyarrow array",flush=True)
>  67
>  68     # to table
>  69     table = pyarrow.Table.from_arrays([pyarrow_array], ["feature"])
>  70     # save to in-memory graph
>  71     original_graph.upsert_node_property(table)
> ```

no, 
```
 42     distributed.initialize()
``` 
would definitely fail. 
Better to keep the add features script in `katana-enterprise` anyway, rather than this public repo, and call it from a wrapper in this repo.

**Comment by l-hoang** [comment]
If I shifted to using a normal Graph and not one from katana_enterprise would things work? I think upsert exists for the shared
memory graph as well.

**Comment by l-hoang** [comment]
> If I shifted to using a normal Graph and not one from katana_enterprise would things work? I think upsert exists for the shared memory graph as well.

actually that looks like it would require `katana.local.initialize()`; is this also a no-go?

**Comment by e-mcginnis** [comment]
> If I shifted to using a normal Graph and not one from katana_enterprise would things work? I think upsert exists for the shared
> memory graph as well.

the katana python api is not imported in this repo. All the existing tooling uses subprocess to call tools in the katana enterprise build dir.

**Comment by e-mcginnis** [comment]
we could add tooling to import the katana python api, but I think that would be more work than you would like it to be :)

**Comment by l-hoang** [comment]
Updated the README to reflect that it's now using a generate script:
https://github.com/KatanaGraph/test-datasets/blob/381bee6a854ef2785858663b481653894bbe3f5e/rdg_datasets/many_self_loops_w_sink_ai/generate.py

requires a katana_enterprise build, though (couldn't get it working with a local build at the moment)

**Comment by l-hoang** [comment]
"local build" in this case means katana.local.graph

I've tested the generate script locally and it works:
```
./uprev  rdgs --rdg many_self_loops_w_sink_ai  --storage_format_version 8 --build_dir /home/loc/build
```

```
TRACE: host=0 ms=8 max_mem_gb=0.282 mem_gb=0.282 arrow_mem_gb=0.000 sent_gb:0.000 recv_gb:0.000 | finished commit distribution
in-place feature add complete
TRACE: host=0 ms=13 max_mem_gb=0.282 mem_gb=0.281 arrow_mem_gb=0.000 sent_gb:0.000 recv_gb:0.000 | finished unnamed span
Succeeded upreving many_self_loops_w_sink_ai
**************************************** Uprev RDG Report ****************************************
******************** Successfully upreved 1 rdgs ********************
         many_self_loops_w_sink_ai at ........./rdg_datasets/many_self_loops_w_sink_ai/storage_format_version_8
```

**Comment by e-mcginnis** [comment]
> "local build" in this case means katana.local.graph
> 
> I've tested the generate script locally and it works:
> 
> ```
> ./uprev  rdgs --rdg many_self_loops_w_sink_ai  --storage_format_version 8 --build_dir /home/loc/build
> ```
> 
> ```
> TRACE: host=0 ms=8 max_mem_gb=0.282 mem_gb=0.282 arrow_mem_gb=0.000 sent_gb:0.000 recv_gb:0.000 | finished commit distribution
> in-place feature add complete
> TRACE: host=0 ms=13 max_mem_gb=0.282 mem_gb=0.281 arrow_mem_gb=0.000 sent_gb:0.000 recv_gb:0.000 | finished unnamed span
> Succeeded upreving many_self_loops_w_sink_ai
> **************************************** Uprev RDG Report ****************************************
> ******************** Successfully upreved 1 rdgs ********************
>          many_self_loops_w_sink_ai at ........./rdg_datasets/many_self_loops_w_sink_ai/storage_format_version_8
> ```

ahhhhh, I get you. Sorry. Too many "locals"

**Review by e-mcginnis — APPROVED** [review]
looks great, thanks Loc!

**Pull request merged**
