### PR TITLE
Add property gid to nodes

### PR DESCRIPTION
**Pull request by YupingLu**
Hi @e-mcginnis , I need to add a column to the nodes.csv. The previous PR was merged by me. Sorry about the inconvenience.

### CODE REVIEW

**Comment by e-mcginnis** [comment]
It looks like this PR contains all of your previous PRs changes, plus the new ones. You should update this PR to include just the diff between the two.

**Comment by YupingLu** [comment]
Hi @e-mcginnis , I have made the change. Can you review and approve the PR? Thx.

**Comment by YupingLu** [comment]
Hi @e-mcginnis , I have made the change. Can you review and approve the PR? Thx.

**Review by e-mcginnis — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
