### PR TITLE
Add a new Smiles dataset for HLS tasks

### PR DESCRIPTION
**Pull request by Hunterlige**
### PR Checklist

* [x] test-datasets is a publicly accessible github repo. The contents of this PR can be made public.
* [x] The naming and organization of the dataset I am adding follows https://github.com/KatanaGraph/test-datasets#organization
* [x] If I am adding an RDG, its directory contains a (import/migrate/generate) script, and a README describing the RDGs usage. https://github.com/KatanaGraph/test-datasets#the-following-scripts-are-conditionally-present-for-each-rdg-one-of-the-following-options-must-be-present
* [x] If I am uprevving the storage_format_version of the rdgs in this repo, I have followed https://github.com/KatanaGraph/test-datasets#how-to-uprev-the-rdgs-in-this-repo

### List of folks that should be notified of this PR. Please don't remove these. 
@scober
@aneeshdurg

Add a new Smiles dataset for HLS tasks. This graph has 3 nodes types: Dataset, Compound and Bad_Compound. This dataset allows us to test more HLS API and pipelines.

### CODE REVIEW

**Comment by e-mcginnis** [comment]
so we already have `smiles_small` csv & rdg, and `bad_smiles` csv & rdg what makes this one different? Can you give it a more unique name?

**Comment by Hunterlige** [comment]
@e-mcginnis This graph has node types (3 nodes types), has edge properties (target value) and node properties (smiles). 
The graph is very similar to the rdg uses for HLS AI pipeline in Drug Target predictions. The old graphs `smiles_small `and `bad_smiles ` do not allow testing functionalities on specific node types. Old graphs does not have edges property and node types and could not be split in 2 partitions without an empty node partition.

I think "smiles" and "small" words should be in the name of the rdg. (current is `smiles_datasets_small`). Do you have anything in mind for _give it a more unique name_ I like this name because RDG is a combination of Smiles datasets,  but I agree that dataset word can be confusing with dataset rdg. Do you agree that something like `smiles_targets_small`  is unique enough ? Or maybe  
`smiles_datasets_predictions_small ` or `smiles_targets_predictions_small `.

**Comment by e-mcginnis** [comment]
> @e-mcginnis This graph has node types (3 nodes types), has edge properties (target value) and node properties (smiles). The graph is very similar to the rdg uses for HLS AI pipeline in Drug Target predictions. The old graphs `smiles_small `and `bad_smiles ` do not allow testing functionalities on specific node types. Old graphs does not have edges property and node types and could not be split in 2 partitions without an empty node partition.
> 
> I think "smiles" and "small" words should be in the name of the rdg. (current is `smiles_datasets_small`). Do you have anything in mind for _give it a more unique name_ I like this name because RDG is a combination of Smiles datasets, but I agree that dataset word can be confusing with dataset rdg. Do you agree that something like `smiles_targets_small` is unique enough ? Or maybe `smiles_datasets_predictions_small ` or `smiles_targets_predictions_small `.

Putting that info in the rdgs README would be really appreciated 


re: the name, `smiles_targets_predictions_small` seems good enough to me.

**Comment by e-mcginnis** [comment]
thanks for those changes, it all looks good to me now. 
I'll let @scober give the final review

**Review by scober — APPROVED** [review]

**Pull request merged**
