### PR TITLE
Remove unused rmat15_transpose RDG

### PR DESCRIPTION
**Pull request by bhargavivadali**
### PR Checklist

* [ ] test-datasets is a publicly accessible github repo. The contents of this PR can be made public.
* [ ] The naming and organization of the dataset I am adding follows https://github.com/KatanaGraph/test-datasets#organization
* [ ] If I am adding an RDG, its directory contains a (import/migrate/generate) script, and a README describing the RDGs usage. https://github.com/KatanaGraph/test-datasets#the-following-scripts-are-conditionally-present-for-each-rdg-one-of-the-following-options-must-be-present
* [ ] If I am uprevving the storage_format_version of the rdgs in this repo, I have followed https://github.com/KatanaGraph/test-datasets#how-to-uprev-the-rdgs-in-this-repo

### List of folks that should be notified of this PR. Please don't remove these. 
@scober
@aneeshdurg

Remove unused rmat15_transpose RDG [KAT-16421]

[KAT-16421]: https://katanagraph.atlassian.net/browse/KAT-16421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by uditagar — APPROVED** [review]
There are also other files that can be removed as well, e.g.  [rmat15_hosts=2_policy=oec], as nobody seems to be using them at the moment. But others can chime in about that.

**Review by gliga — APPROVED** [review]
LG

but you should first delete the line from enterprise

**Comment by gliga** [comment]
@uditagar we will get to other graphs as well; doing a bit more step-by-step approach.

**Comment by bhargavivadali** [comment]
> LG
> 
> but you should first delete the line from enterprise

Already created a PR in enterprise repo https://github.com/KatanaGraph/katana-enterprise/pull/7562

**Review by scober — APPROVED** [review]

**Pull request merged**
