### PR TITLE
Kat 6031

### PR DESCRIPTION
**Pull request by bhargavivadali**
### PR Checklist

* [ ] test-datasets is a publicly accessible github repo. The contents of this PR can be made public.
* [ ] The naming and organization of the dataset I am adding follows https://github.com/KatanaGraph/test-datasets#organization
* [ ] If I am adding an RDG, its directory contains a (import/migrate/generate) script, and a README describing the RDGs usage. https://github.com/KatanaGraph/test-datasets#the-following-scripts-are-conditionally-present-for-each-rdg-one-of-the-following-options-must-be-present
* [ ] If I am uprevving the storage_format_version of the rdgs in this repo, I have followed https://github.com/KatanaGraph/test-datasets#how-to-uprev-the-rdgs-in-this-repo

### List of folks that should be notified of this PR. Please don't remove these. 
@e-mcginnis
@aneeshdurg

The ldbc_003 CSV dataset in this repo is old and its nodes/edges count doesn't match the dataset in GCS/S3. This PR replaces csv and parquet ldbc 003 files. [KAT-6031]. Saving a copy of existing files in ldbc_old dir until the transition is complete.
New csv files are from `gs://katana-demo-datasets/csv-datasets/ldbc/sf-0.003/csv/bi/composite-projected-fk/initial_snapshot` and parquet files from `gs://katana-demo-datasets/parquet-datasets/ldbc/sf-0.003/parquet/bi/composite-projected-fk/initial_snapshot`

[KAT-6031]: https://katanagraph.atlassian.net/browse/KAT-6031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by gliga** [comment]
Are all tests (Python and C++) passing locally with these changes?

**Comment by aneeshdurg** [comment]
Cc @danielmawhirter

**Comment by e-mcginnis** [comment]
is the plan to regenerate the ldbc* rdgs using this csv in another PR?

**Comment by VhalPurohit** [comment]
@bhargavivadali old how, I was wondering. Is this in terms of the schema?

**Comment by gliga** [comment]
@VhalPurohit in the test-datasets we have ldbc v3 I believe and on gs we have ldbc v4.  This move that @bhargavivadali is doing is to include ldbc from gs to our test-datasets.

The question you are asking is great.  @bhargavivadali is not touching any of the headers at this point, but since we are doing this move it might as well be worth doing both things (probably still in a sequence of two commits).  Can you link to your header update here, so we can do both of those tasks.

**Comment by VhalPurohit** [comment]
@gliga here's the link to that PR https://github.com/KatanaGraph/test-datasets/pull/8

**Comment by scober** [comment]
I have a question as an aspiring test-datasets maintainer. If we regenerate the ldbc RDGs from CSV/Parquet then will we lose those RDGs in all the old storage versions? And does that matter? Do we need to maintain more than one RDG in multiple versions to test version upgrades?

**Comment by aneeshdurg** [comment]
@scober not if we use the same csv files. But a couple times in the past we've changed the csv files themselves and regenerated them. I don't know the exact reasons why, but I think one of them is that the ldbc committee changed the generation script or something at one point?

**Comment by scober** [comment]
@aneeshdurg I think my real concern is that we are going to lose institutional knowledge about how to build and run old versions of the code. And as time goes on the cost of regenerating old versions will get higher. Maybe what I want is 'dev run test-datasets' or something similar. Because that combined with GitHub tags marking storage format changes would let us easily generate RDGs for every storage format version when we add new datasets or modify old ones.

**Comment by e-mcginnis** [comment]
> I have a question as an aspiring test-datasets maintainer. If we regenerate the ldbc RDGs from CSV/Parquet then will we lose those RDGs in all the old storage versions? And does that matter? Do we need to maintain more than one RDG in multiple versions to test version upgrades?

Not necessarily, we could just regenerate ldbc for the current storage_format_version and keep the old ones as is.

> Maybe what I want is 'dev run test-datasets' or something similar

That would be neat. The only real reason the `uprev` scripts aren't part of `dev` is that `dev` was not as mature as it is now. Some care would have to be taken to ensure the way we collect the available rdg scripts still works when packed into dev. A goal of uprev was that it would not have to keep a list of available rdgs in test-datasets. https://github.com/KatanaGraph/test-datasets/blob/master/rdg_datasets/__init__.py handles that. There are likely more clever ways to achieve this though. 

Another small catch is that a couple rdgs require manual steps to generate them, ex:
https://github.com/KatanaGraph/test-datasets/tree/master/rdg_datasets/ldbc_003_split_prop
https://github.com/KatanaGraph/test-datasets/tree/master/rdg_datasets/ldbc_003_maximal
- split prop could be made automatic with some feature flag in the main repos code
- maximal purposely requires manual intervention to ensure whoever uprevs the rdgs puts thought into what the new "maximal" rdg should be. I'd love to get rid of maximal altogether, but its still necessary to avoid accidental changes to the storage_format... I'll avoid getting too much into that here.

**Comment by scober** [comment]
> Maybe we should also have a process around depreciating a version and removing it from master of test-datasets? It'll still be in the git history anyway

I'm less sure about this one. I think ideally we would never deprecate a storage format version.

**Comment by bhargavivadali** [comment]
> is the plan to regenerate the ldbc* rdgs using this csv in another PR?

yes

**Comment by bhargavivadali** [comment]
> Are all tests (Python and C++) passing locally with these changes?

yes I ran both python and c++ tests locally.

**Comment by gliga** [comment]
Is there a corresponding PR that is updating tests in katana-enterprise?  At least updating the dataset class for ldbc 003 will be needed as the numbers of nodes and edges change.

**Comment by bhargavivadali** [comment]
> Is there a corresponding PR that is updating tests in katana-enterprise? At least updating the dataset class for ldbc 003 will be needed as the numbers of nodes and edges change.

I need to update both test-datasets SHA in example_data.py and modify nodes/edges count. I can PR once this is merged.

**Review by gliga — APPROVED** [review]
Let's move!

LG

**Pull request merged**
